MOV DPTR,#4500H
MOVX A,@ DPTR
MOV R0,A
INC DPTR
MOV R1,DPL
MOV R2,DPH
MOV DPTR,#4510H
L1: PUSH DPL
      PUSH DPH
      MOV DPL,R1
      MOV DPH,R2
      MOVX A,@ DPTR
      INC DPTR
      MOV R1,DPL
      MOV R2,DPH
      POP DPH
      POP DPL
      MOVX @ DPTR,A
      INC DPTR
DJNZ R0,L1
END